BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "Specialties" (
    "Code" varchar(50) PRIMARY KEY,
    "Name" varchar(100) NOT NULL,
    "Description" varchar(500) NOT NULL DEFAULT '',
    "Category" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS "Hospitals" (
    "Id" varchar(50) PRIMARY KEY,
    "Name" varchar(200) NOT NULL,
    "Code" varchar(50) NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "Address" varchar(500) NOT NULL DEFAULT '',
    "Phone" varchar(50) NOT NULL DEFAULT '',
    "Email" varchar(200),
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL DEFAULT now(),
    "IsActive" boolean NOT NULL DEFAULT true,
    "CurrentQueue_HospitalId" text,
    "CurrentQueue_SpecialtyCode" varchar(50),
    "CurrentQueue_CurrentLength" integer,
    "CurrentQueue_CurrentServingNumber" integer,
    "CurrentQueue_EstimatedWaitMinutes" integer,
    "CurrentQueue_ServingVelocityPerHour" double precision,
    "CurrentQueue_DoctorQuota" integer,
    "CurrentQueue_DoctorsOnDuty" integer,
    "CurrentQueue_LastUpdated" timestamp with time zone,
    "CurrentQueue_Status" integer,
    CONSTRAINT "UQ_Hospitals_Code" UNIQUE ("Code")
);

CREATE INDEX IF NOT EXISTS "IX_Hospitals_Latitude_Longitude"
    ON "Hospitals" ("Latitude", "Longitude");

CREATE TABLE IF NOT EXISTS "HospitalSpecialty" (
    "HospitalId" varchar(50) NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SpecialtyCode" varchar(50) NOT NULL,
    "Name" varchar(100) NOT NULL,
    "Category" integer NOT NULL,
    PRIMARY KEY ("HospitalId", "Id"),
    CONSTRAINT "FK_HospitalSpecialty_Hospitals"
        FOREIGN KEY ("HospitalId") REFERENCES "Hospitals" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_HospitalSpecialty_SpecialtyCode"
    ON "HospitalSpecialty" ("SpecialtyCode");

CREATE TABLE IF NOT EXISTS "HospitalBedCapacity" (
    "HospitalId" varchar(50) NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Class" varchar(20) NOT NULL,
    "Total" integer NOT NULL CHECK ("Total" >= 0),
    "Occupied" integer NOT NULL CHECK ("Occupied" >= 0 AND "Occupied" <= "Total"),
    "LastUpdated" timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY ("HospitalId", "Id"),
    CONSTRAINT "FK_HospitalBedCapacity_Hospitals"
        FOREIGN KEY ("HospitalId") REFERENCES "Hospitals" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "BedCapacities" (
    "HospitalId" varchar(50) NOT NULL,
    "Class" varchar(20) NOT NULL,
    "Total" integer NOT NULL CHECK ("Total" >= 0),
    "Occupied" integer NOT NULL CHECK ("Occupied" >= 0 AND "Occupied" <= "Total"),
    "LastUpdated" timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY ("HospitalId", "Class")
);

CREATE TABLE IF NOT EXISTS "Queues" (
    "HospitalId" varchar(50) NOT NULL,
    "SpecialtyCode" varchar(50) NOT NULL,
    "CurrentLength" integer NOT NULL DEFAULT 0,
    "CurrentServingNumber" integer NOT NULL DEFAULT 0,
    "EstimatedWaitMinutes" integer NOT NULL DEFAULT 0,
    "ServingVelocityPerHour" double precision NOT NULL DEFAULT 0,
    "DoctorQuota" integer NOT NULL DEFAULT 0,
    "DoctorsOnDuty" integer NOT NULL DEFAULT 0,
    "LastUpdated" timestamp with time zone NOT NULL DEFAULT now(),
    "Status" integer NOT NULL,
    PRIMARY KEY ("HospitalId", "SpecialtyCode")
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "Email" varchar(320) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" varchar(200) NOT NULL,
    "Role" varchar(30) NOT NULL DEFAULT 'USER',
    "IsActive" boolean NOT NULL DEFAULT true,
    "EmailVerifiedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Email"
    ON "Users" (lower("Email"));

CREATE TABLE IF NOT EXISTS "PasswordResetTokens" (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "UserId" uuid NOT NULL,
    "TokenHash" char(64) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "FK_PasswordResetTokens_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_PasswordResetTokens_TokenHash"
    ON "PasswordResetTokens" ("TokenHash");

CREATE INDEX IF NOT EXISTS "IX_PasswordResetTokens_UserId_ExpiresAt"
    ON "PasswordResetTokens" ("UserId", "ExpiresAt");

COMMIT;
